force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/Module_Progress__c.object-meta.xml
<CustomObject>
    <label>Module Progress</label>
    <nameField>
        <label>Module Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Module Progresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Module Progresses</relationshipLabel>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Progress__c/Unit_Progress__c.object-meta.xml
<CustomObject>
    <label>Unit Progress</label>
    <nameField>
        <label>Unit Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Progress__c/fields/Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Module_Progress__c</fullName>
    <label>Module Progress</label>
    <referenceTo>Module_Progress__c</referenceTo>
    <relationshipLabel>Unit Progresses</relationshipLabel>
    <relationshipName>Unit_Progresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/fields/Points_Obtained__c.field-meta.xml
<CustomField>
    <fullName>Points_Obtained__c</fullName>
    <label>Points Obtained</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Progresses</relationshipLabel>
    <relationshipName>Unit_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/fields/Unit_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Unit_Attempts__c</fullName>
    <label>Unit Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Answer__c/User_Answer__c.object-meta.xml
<CustomObject>
    <label>User Answer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>User Answers</relationshipLabel>
    <relationshipName>User_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>User Answers</relationshipLabel>
    <relationshipName>User_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Answer__c/fields/Unit_Progress__c.field-meta.xml
<CustomField>
    <fullName>Unit_Progress__c</fullName>
    <label>Unit Progress</label>
    <referenceTo>Unit_Progress__c</referenceTo>
    <relationshipLabel>User Answers</relationshipLabel>
    <relationshipName>User_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UnitService.cls
public with sharing class UnitService {
    
    @AuraEnabled(cacheable= false)  
    public static void submitAnswer(Id unitId, String answerJson) {
        // Get the current user
        Id userId = UserInfo.getUserId();
               
        // Get the corresponding Unit Progress record for the user and unit
        List<Unit_Progress__c> unitProgressRecords = [SELECT Id, Status__c, Unit_Attempts__c, Module_Progress__r.Status__c, Unit__r.Module__c FROM Unit_Progress__c WHERE Module_Progress__r.User__c = :userId AND Unit__c = :unitId];
        
        Unit_Progress__c unitProgress = null;
        Module_Progress__c moduleProgress = null;
        List<User_Answer__c> userAnswersToUpsert = new List<User_Answer__c>();
        
        if (unitProgressRecords.size() == 0) {
            // Create new Unit Progress record and Module Progress record if they don't exist yet
            List<Unit__c> relatedUnits = [SELECT Name, Module__c, Module__r.Name FROM Unit__c WHERE Id = :unitId LIMIT 1];
            if (relatedUnits.size() > 0) {
                Unit__c relatedUnit = relatedUnits[0];
                moduleProgress = [SELECT Id FROM Module_Progress__c WHERE Module__c = :relatedUnit.Module__c AND User__c = :userId LIMIT 1];
                if (moduleProgress == null) {
                    moduleProgress = new Module_Progress__c(
                        Name = relatedUnit.Module__r.Name,
                        User__c = userId,
                        Module__c = relatedUnit.Module__c,
                        Status__c = 'In Progress'
                    );
                    insert moduleProgress;
                }
                unitProgress = new Unit_Progress__c(
                    Name = relatedUnit.Name,
                    User__c = userId,
                    Completed__c = false,
                    Points_Obtained__c = 0,            
                    Unit__c = unitId,
                    Status__c = 'Draft',
                    Unit_Attempts__c = 1,
                    Module_Progress__c = moduleProgress.Id
                );
                insert unitProgress;
            }
        } else {
            // Update existing Unit Progress record
            unitProgress = unitProgressRecords[0];
            unitProgress.Unit_Attempts__c ++;
            unitProgress.Status__c = 'Draft';
            update unitProgress;
            // Delete existing User Answer records
            List<User_Answer__c> existingUserAnswers = [SELECT Id FROM User_Answer__c WHERE Unit_Progress__c = :unitProgress.Id];
            delete existingUserAnswers;
        }
                     
        // Parse answer JSON and create new User Answer records
        Map<Id, Id> answerMap = (Map<Id, Id>)JSON.deserializeStrict(answerJson, Map<Id, Id>.class);  
        for (String questionId : answerMap.keySet()) {
            User_Answer__c userAnswer = new User_Answer__c(
                Question__c = questionId,
                Answer__c = answerMap.get(questionId),
                Unit_Progress__c = unitProgress.Id
            );
            userAnswersToUpsert.add(userAnswer);
        }
        upsert userAnswersToUpsert;
        
        // Update Unit Progress record status to "Answered"
        if (unitProgress != null) {
            unitProgress.Status__c = 'Answered';
            update unitProgress;
        }
    }
    

    @AuraEnabled(cacheable = true)
    public static TrailWrapper getTrailWrapper(Id trailId) {
        TrailWrapper tw = new TrailWrapper(trailId);
        return tw;
    }
    
    @AuraEnabled(cacheable = true)
    public static UnitWrapper getUnitWrapper(Id unitId) {  
        UnitWrapper uw = new UnitWrapper(unitId);
        return uw;
    }
    
}