force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Answer__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Correct_Answer__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Correct_Answer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <description>Points acumulated in related units.</description>
    <label>Total Points</label>
    <summarizedField>Unit__c.Total_Points__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <formula>TEXT(Time__c) + &quot; Mins&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <description>Units total points.</description>
    <label>Total Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UnitWrapper.cls
public class UnitWrapper {
    public Unit__c unit;
    public List<QuestionWrapper> questions;

    public UnitWrapper(Id unitId) {
        // Query the Unit record and populate the unit field
        unit = [SELECT Id, Name, Content__c, Total_Points__c, Estimated_Time__c, Module__c
                FROM Unit__c
                WHERE Id = :unitId];
        
        // Query the related questions and options and populate the questions field
        List<Question__c> unitQuestions = [SELECT Id, Name, Content__c, Unit__c
                                           FROM Question__c
                                           WHERE Unit__c = :unitId];
        questions = new List<QuestionWrapper>();
        for (Question__c q : unitQuestions) {
            questions.add(new QuestionWrapper(q.Id));
        }
    }

    public class QuestionWrapper {
        public Question__c question;
        public List<Answer__c> options;
        public String userAnswer;

        public QuestionWrapper(Id questionId) {
            // Query the Question record and populate the question field
            question = [SELECT Id, Name, Content__c, Unit__c FROM Question__c WHERE Id = :questionId];
            
            // Query the related options and populate the options field
            options = [SELECT Id, Name, Content__c, Correct_Answer__c FROM Answer__c WHERE Question__c = :questionId];
        }
    }
}