force-app/main/default/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <label>Answer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <description>Points acumulated in related units.</description>
    <label>Total Points</label>
    <summarizedField>Unit__c.Total_Points__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/Module_Progress__c.object-meta.xml
<CustomObject>
    <label>Module Progress</label>
    <nameField>
        <label>Module Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Module Progresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Module Progresses</relationshipLabel>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <label>Total Points</label>
    <summarizedField>Unit_Progress__c.Points_Obtained__c</summarizedField>
    <summaryForeignKey>Unit_Progress__c.Module_Progress__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <description>Units total points.</description>
    <label>Total Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/Unit_Progress__c.object-meta.xml
<CustomObject>
    <label>Unit Progress</label>
    <nameField>
        <label>Unit Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Progress__c/fields/Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Module_Progress__c</fullName>
    <label>Module Progress</label>
    <referenceTo>Module_Progress__c</referenceTo>
    <relationshipLabel>Unit Progresses</relationshipLabel>
    <relationshipName>Unit_Progresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Progresses</relationshipLabel>
    <relationshipName>Unit_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/fields/Unit_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Unit_Attempts__c</fullName>
    <label>Unit Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Answer__c/User_Answer__c.object-meta.xml
<CustomObject>
    <label>User Answer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>User Answers</relationshipLabel>
    <relationshipName>User_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>User Answers</relationshipLabel>
    <relationshipName>User_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Answer__c/fields/Unit_Progress__c.field-meta.xml
<CustomField>
    <fullName>Unit_Progress__c</fullName>
    <label>Unit Progress</label>
    <referenceTo>Unit_Progress__c</referenceTo>
    <relationshipLabel>User Answers</relationshipLabel>
    <relationshipName>User_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UnitServiceTest.cls
@IsTest
public class UnitServiceTest {
    
    @IsTest
    static void testSubmitAnswer() {
        
        // Crear un nuevo usuario
        User usuarioPrueba = new User(
            FirstName = 'Pepe',
            LastName = 'Pompin',
            Email = 'pepetest@test.com',
            Alias = 'pepito',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'es',
            LocaleSidKey = 'es_AR',
            TimeZoneSidKey = 'America/Argentina/Buenos_Aires',
            Username = 'pepetesting@test.com'
            
         );
        insert usuarioPrueba;
        
        // Crear un nuevo módulo
        Module__c moduloPrueba = new Module__c(
            Name = 'Módulo de prueba'
        );
        insert moduloPrueba;
        
        // Crear una nueva unidad
        Unit__c unidadPrueba = new Unit__c(
            Name = 'Unidad de prueba', 
            Module__c = moduloPrueba.Id, 
            Total_Points__c = 400
        );
        insert unidadPrueba;
        
        // Configurar los datos de prueba
        Module_Progress__c progresoModulo = new Module_Progress__c(
            User__r = usuarioPrueba, // Usar User__r en lugar de User__c
            Module__r = moduloPrueba, // Usar Module__r en lugar de Module__c
            Name = 'Progreso del módulo de prueba'
        );
        insert progresoModulo;
        
        Unit_Progress__c unidadProgresoPrueba = new Unit_Progress__c(
            Unit__c = unidadPrueba.Id,
            Module_Progress__c = progresoModulo.Id // Usar la ID del registro de progreso del módulo insertado
        );
        insert unidadProgresoPrueba;
        
        Map<String, Object> respuestasPrueba = new Map<String, Object>{
            'pregunta1' => 'opcion1',
            'pregunta2' => 'opcion2',
            'pregunta3' => 'opcion3'
        };
        
        // Llamar al método submitAnswer
        Test.startTest();
        UnitService.submitAnswer(unidadPrueba.Id, JSON.serialize(respuestasPrueba));
        Test.stopTest();
        
        // Verificar que el registro de progreso de la unidad se actualizó correctamente
        Unit_Progress__c unidadProgresoActualizada = [SELECT Id, Status__c, Unit_Attempts__c FROM Unit_Progress__c WHERE Id = :unidadProgresoPrueba.Id];
        System.assertEquals('Answered', unidadProgresoActualizada.Status__c);
        System.assertEquals(1, unidadProgresoActualizada.Unit_Attempts__c);
        
        // Verificar que se crearon registros de respuesta de usuario
        List<User_Answer__c> respuestasUsuario = [SELECT Id, Question__c, Answer__c, Unit_Progress__c FROM User_Answer__c WHERE Unit_Progress__c = :unidadProgresoPrueba.Id];
        System.assertEquals(3, respuestasUsuario.size());
        System.assertEquals('opcion1', respuestasUsuario[0].Answer__c);
        System.assertEquals('opcion2', respuestasUsuario[1].Answer__c);
        System.assertEquals('opcion3', respuestasUsuario[2].Answer__c);
    }
}