force-app/main/default/objects/Module__c/Module__c.object-meta.xml
<CustomObject>
    <label>Module</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>App Lifecycle</fullName>
            </value>
            <value>
                <fullName>App Logic</fullName>
            </value>
            <value>
                <fullName>Database</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Lightning</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Module__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <description>Points acumulated in related units.</description>
    <label>Total Points</label>
    <summarizedField>Unit__c.Total_Points__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module__c/fields/Total_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Time__c</fullName>
    <label>Total Time</label>
    <summarizedField>Unit__c.Time__c</summarizedField>
    <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/Module_Progress__c.object-meta.xml
<CustomObject>
    <label>Module Progress</label>
    <nameField>
        <label>Module Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Module Progresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Module_Progress__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Module Progresses</relationshipLabel>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <formula>IF( Module__r.Total_Units__c  &gt; 0, Unit_Progress_Check__c / Module__r.Total_Units__c * 100, 0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <label>Total Points</label>
    <summarizedField>Unit_Progress__c.Points_Obtained__c</summarizedField>
    <summaryForeignKey>Unit_Progress__c.Module_Progress__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Module_Progress__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Module_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trail__c/Trail__c.object-meta.xml
<CustomObject>
    <label>Trail</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <label>Total Points</label>
    <summarizedField>Trail_Module__c.Points__c</summarizedField>
    <summaryForeignKey>Trail_Module__c.Trail__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trail__c/fields/Total_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Time__c</fullName>
    <label>Total Time</label>
    <summarizedField>Trail_Module__c.Estimated_Time__c</summarizedField>
    <summaryForeignKey>Trail_Module__c.Trail__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/Trail_Module__c.object-meta.xml
<CustomObject>
    <label>Trail Module</label>
    <nameField>
        <label>Trail Module Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trail Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trail_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipName>Trail_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trail_Module__c/fields/Trail__c.field-meta.xml
<CustomField>
    <fullName>Trail__c</fullName>
    <label>Trail</label>
    <referenceTo>Trail__c</referenceTo>
    <relationshipName>Trail_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Estimated_Time__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Time__c</fullName>
    <formula>TEXT(Time__c) + &quot; Mins&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Total_Points__c.field-meta.xml
<CustomField>
    <fullName>Total_Points__c</fullName>
    <description>Units total points.</description>
    <label>Total Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/Unit_Progress__c.object-meta.xml
<CustomObject>
    <label>Unit Progress</label>
    <nameField>
        <label>Unit Progress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit Progresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Progress__c/fields/Module_Progress__c.field-meta.xml
<CustomField>
    <fullName>Module_Progress__c</fullName>
    <label>Module Progress</label>
    <referenceTo>Module_Progress__c</referenceTo>
    <relationshipLabel>Unit Progresses</relationshipLabel>
    <relationshipName>Unit_Progresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit_Progress__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Progresses</relationshipLabel>
    <relationshipName>Unit_Progresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrailWrapper.cls
public class TrailWrapper {
    
    @AuraEnabled
    public Trail__c trail;
    @AuraEnabled
    public Integer progressTrail;
    @AuraEnabled
    public List<Module__c> modules = new List<Module__c>();
    @AuraEnabled
    public List<Unit__c> units = new List<Unit__c>();
    @AuraEnabled
    public Map<Id, Boolean> completedModuleMap = new Map<Id, Boolean>();
    @AuraEnabled
    public Map<Id, Boolean> completedUnitMap = new Map<Id, Boolean>();
    
    public TrailWrapper(Id trailId) {
        
        
        Id userId = UserInfo.getUserId();
   
        trail = [SELECT Id, Name, Description__c, Total_Points__c, Total_Time__c 
                          FROM Trail__c 
                          WHERE Id = :trailId];
        
        this.trail = trail;
      

        List<Module__c> modules = [SELECT Id, Name, Description__c, Total_Points__c, Total_Time__c, Skills__c,
                                   (SELECT Status__c, Progress__c FROM Module_Progresses__r WHERE User__c = :userId LIMIT 1)
                                   FROM Module__c 
                                   WHERE Id IN 
                                       (SELECT Module__c 
                                        FROM Trail_Module__c 
                                        WHERE Trail__c = :trailId)];
        
        this.modules = modules;
        
        for (Module__c module : modules) {
            if (module.Module_Progresses__r.size() > 0) {
                completedModuleMap.put(module.Id, module.Module_Progresses__r[0].Status__c == 'Completed');
            } else {
                completedModuleMap.put(module.Id, false);
            }
        }

        List<Unit__c> units = [SELECT Id, Name, Content__c, Total_Points__c, Estimated_Time__c, Module__c,
                                (SELECT Completed__c FROM Unit_Progresses__r WHERE Module_Progress__r.User__c = :userId)
                                FROM Unit__c 
                                WHERE Module__c IN :modules];

        this.units = units;

        for (Unit__c unit : units) {
            if (unit.Unit_Progresses__r.size() > 0) {
                completedUnitMap.put(unit.Id, unit.Unit_Progresses__r[0].Completed__c == true);
            } else {
                completedUnitMap.put(unit.Id, false);
            }
        }
        
        this.completedModuleMap = completedModuleMap;
        this.completedUnitMap = completedUnitMap;
        
        this.progressTrail = calculateProgressTrail(trailId); 
    }

    public Integer calculateProgressTrail(Id trailId) {
        
        Integer totalModules = modules.size();
        Integer completedModules = 0;
        Integer totalUnits = 0;
        Integer completedUnits = 0;
    
        for (Module__c module : modules) {
            if (completedModuleMap.get(module.Id)) {
                completedModules++;
            }
            totalUnits += module.Units__r.size();
            for (Unit__c unit : module.Units__r) {
                if (completedUnitMap.get(unit.Id)) {
                    completedUnits++;
                }
            }
        }
    
        Integer progress = 0;
    
        if (totalUnits > 0) {
            progress = Math.round((completedUnits / totalUnits) * 100);
        } else if (totalModules > 0) {
            progress = Math.round((completedModules / totalModules) * 100);
        }
    
        return progress; 
    }

    @AuraEnabled(cacheable = true)
    public static TrailWrapper getTrailId(Id moduleId) {
        
        Trail_Module__c trailModule = [SELECT Id, Trail__c FROM Trail_Module__c WHERE Module__c = :moduleId LIMIT 1];

        return new TrailWrapper(trailModule.Trail__c);
        
    }

}